First full students service implementation
Paxing939/EducationalAccountingSystem pull request #6
Opened 2024-12-18 21:07 UTC by DelovoiDC

2024-12-19 11:26 UTC, Paxing939 requested changes

2024-12-19 11:26 UTC, Paxing939 commented on students/students_service.py
> +<<<<<<< HEAD
Откуда столько мерж конфликтов?

2024-12-19 11:26 UTC, Paxing939 commented on students/students_service.py
> +>>>>>>> bbc946f (First full students service implementation)
Разрешить мерж конфликт

2024-12-19 11:26 UTC, Paxing939 commented on students/students_service.py
> +<<<<<<< HEAD
Разрешить мерж конфликт

2024-12-19 11:26 UTC, Paxing939 commented on students/students_service.py
> +<<<<<<< HEAD
Разрешить мерж конфликт

2024-12-19 11:26 UTC, Paxing939 commented on students/students_service.py
> +<<<<<<< HEAD
Разрешить мерж конфликт

2024-12-19 12:46 UTC, Paxing939 commented on students/requirements.txt
> +greenlet==3.1.1
Зачем лишние пакеты тут? мы же их не импортируем

2024-12-19 12:48 UTC, DelovoiDC commented on students/requirements.txt
> +greenlet==3.1.1
Лишние пакеты являются зависимостями используемых пакетов

2025-01-02 15:34 UTC, Paxing939 approved these changes

2025-01-02 15:34 UTC, merged